workflows:
  ios-build:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default      # Adăugat pentru a gestiona mai bine instalarea pod-urilor
    scripts:
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Pod install
        script: |
          cd ios
          pod deintegrate
          pod cache clean --all
          pod install
          cd ..
      - name: Build iOS app (no signing)
        script: |
          flutter build ios --release --no-codesign --no-tree-shake-icons
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - elitattoobrasov@gmail.com
