// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb, defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 🔹 CONFIGURARE WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB6bUWN6JD4RCN8a3_O-O6Rno1gudaVXvU",
    authDomain: "elitattoo-app-c7763.firebaseapp.com",
    projectId: "elitattoo-app-c7763",
    storageBucket: "elitattoo-app-c7763.appspot.com",
    messagingSenderId: "485612502628",
    appId: "1:485612502628:web:2ae8babceb07bda3d0a971",
    measurementId: "G-8S7JB0YF8E",
  );

  // 🔹 CONFIGURARE ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBKBHgJkzUBoO9y0DyPRCq8I5CU16sSPRU",
    appId: "1:244765485886:android:xxxxxxxxxxxxxx",
    messagingSenderId: "244765485886",
    projectId: "elitattoo-app",
    storageBucket: "elitattoo-app.appspot.com",
  );

  // 🔹 CONFIGURARE iOS & macOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCfeEYbhLkRnO9JuhlDkE7w8tz9Dd0p0Zk",
    appId: "1:244765485886:ios:xxxxxxxxxxxxxx",
    messagingSenderId: "244765485886",
    projectId: "elitattoo-app",
    storageBucket: "elitattoo-app.appspot.com",
    iosClientId: "244765485886-rg32rsn4jgeejmroumbpd4ngkg2hgvp4.apps.googleusercontent.com",
    iosBundleId: "com.example.eliTattooClienti",
  );

  static const FirebaseOptions macos = ios; // macOS folosește aceeași configurare ca iOS

  // 🔹 CONFIGURARE WINDOWS
  static const FirebaseOptions windows = web; // Windows folosește aceeași configurare ca Web
}
