// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbOGqgBB1htpneQ8bnxdIlWhsxWRKYNvQ',
    appId: '1:485612502628:web:41ab29297c499a80d0a971',
    messagingSenderId: '485612502628',
    projectId: 'elitattoo-app-c7763',
    authDomain: 'elitattoo-app-c7763.firebaseapp.com',
    storageBucket: 'elitattoo-app-c7763.firebasestorage.app',
    measurementId: 'G-E0ZR4KLDR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-NzCgBePeBHqkVwOsvfaiORVVbz7UdT4',
    appId: '1:485612502628:android:680b33dc6f8eec50d0a971',
    messagingSenderId: '485612502628',
    projectId: 'elitattoo-app-c7763',
    storageBucket: 'elitattoo-app-c7763.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5LlKIz1lV2DGuaQ-P11eTOxs8FQ8pqrk',
    appId: '1:485612502628:ios:8186014fb9e3c7e3d0a971',
    messagingSenderId: '485612502628',
    projectId: 'elitattoo-app-c7763',
    storageBucket: 'elitattoo-app-c7763.firebasestorage.app',
    androidClientId: '485612502628-2kp77j7cg4pqiugdk45mfk332ej2fapj.apps.googleusercontent.com',
    iosClientId: '485612502628-r2sph92s2pjdo9g8jqq21mq4515ic8h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.eliTattooClienti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5LlKIz1lV2DGuaQ-P11eTOxs8FQ8pqrk',
    appId: '1:485612502628:ios:0e91b9409d8ac6f7d0a971',
    messagingSenderId: '485612502628',
    projectId: 'elitattoo-app-c7763',
    storageBucket: 'elitattoo-app-c7763.firebasestorage.app',
    androidClientId: '485612502628-2kp77j7cg4pqiugdk45mfk332ej2fapj.apps.googleusercontent.com',
    iosClientId: '485612502628-inqo03ib6t6hbmkauttu2umrukh0ts8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.eliTattooClientiNou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbOGqgBB1htpneQ8bnxdIlWhsxWRKYNvQ',
    appId: '1:485612502628:web:2f7a48a5be2f24e1d0a971',
    messagingSenderId: '485612502628',
    projectId: 'elitattoo-app-c7763',
    authDomain: 'elitattoo-app-c7763.firebaseapp.com',
    storageBucket: 'elitattoo-app-c7763.firebasestorage.app',
    measurementId: 'G-W8P6EMHGQ1',
  );
}
